project/models.py
from datetime import datetime
from email.policy import default
from enum import unique
from project import db
from flask_login import UserMixin
from . import login_manager


class User(UserMixin, db.Model):
    user_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    phone = db.Column(db.BigInteger, unique=True, nullable=False)
    password = db.Column(db.String(50), nullable=False)
    login_time = db.Column(db.DateTime, nullable=False,
                           default=datetime.utcnow)
    email_verified = db.Column(db.Boolean, default=0)

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def __repr__(self):
        return f"User('{self.name}','{self.email}','{self.phone}','{self.password}')"

    def get_id(self):
        return (self.user_id)

    def update(self):
        db.session.commit()

project/__init__.py
# from crypt import methods

from flask import Flask, session
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime, timedelta
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from smtplib import SMTP


app = Flask(__name__)
app.config['SECRET_KEY'] = "thisisrequired"
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://stonex:Stonex&123@localhost/login_sys'
app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False
app.permanent_session_lifetime = timedelta(minutes=1)


db = SQLAlchemy(app)


login_manager = LoginManager(app)
login_manager.init_app(app)
login_manager.login_view = 'my_view.login'


# ===================================================================
#                       BLUEPRINTS
# ===================================================================
from project.views.app_views import app_blueprint
app.register_blueprint(app_blueprint)

project/views/app_views.py
# from project import app
from .. import login_manager
from flask import flash, redirect, render_template, request, Blueprint, url_for, session
from forms import loginForm, registrationForm, resetPasswordForm, emailVerificationForm
from project.models import User
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from ..helper import sendEmail, generateOTP


app_blueprint = Blueprint('my_view', __name__)
data = {}


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# -----------------------INDEX-----------------------------

@app_blueprint.route('/')
def index():
    return render_template('index.html')

# ---------------------HOME--------------------------------

@app_blueprint.route('/home')
@login_required
def home():
    return render_template('home.html')


# -------------------------LOGIN--------------------------


@app_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = loginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            email=form.username.data, password=form.password.data).first()
        if user:
            session['email'] = user.email
            if(not user.email_verified):
                data['otp'] = generateOTP()
                sendEmail(user.email, data['otp'])
                data['fromReg'] = False
                login_user(user)
                flash("Enter OTP sent on your mail to verify", "info")
                return redirect(url_for('my_view.email_verification'))
            login_user(user)
            flash('login successful')
            return redirect(url_for('my_view.home'))
        else:
            flash('Login unsuccessful Please check username and password', 'danger')
    return render_template('login.html', form=form)


# ---------------------REGISTRATION-----------------------

@app_blueprint.route('/regi', methods=['GET', 'POST'])
def registrationform():
    form = registrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            u1 = User(name=form.name.data, phone=form.phone.data,
                      email=form.email.data, password=form.password.data)
            u1 = u1.save()
            data['otp'] = generateOTP()
            data['fromReg'] = True
            session['email'] = form.email.data
            sendEmail(form.email.data, data['otp'])
            flash("Enter OTP sent on your mail to verify", "info")
            return redirect(url_for('my_view.email_verification'))
    return render_template('registration.html', form=form)


# ---------------------RESET--------------------------------

@app_blueprint.route('/reset', methods=['GET', 'POST'])
def reset():
    form = resetPasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            return '<h1> The  New Password is {}'.format(form.new_password.data)
        return render_template('reset.html', form=form)
    return render_template('reset.html', form=form)

# ------------------------EMAIL_VERIFICATION--------------------------

@app_blueprint.route('/email_verification', methods=['GET', 'POST'])
def email_verification():
    form = emailVerificationForm()
    otp = data['otp']
    if request.method == 'POST':
        if form.validate_on_submit():
            if(otp == form.otp_field.data):
                user = User.query.filter_by(email=session['email']).first()
                user.email_verified = 1
                user.update()
                if(data['fromReg']):
                    return redirect(url_for('my_view.login'))
                flash("Email Verified!!")
                return redirect(url_for('my_view.home'))
            flash("Invalid OTP!!")
            return redirect(url_for('my_view.email_verification'))
    return render_template('email_verification.html', form=form)

# -----------------------------LOGOUT---------------------------------------

@app_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout Successful!!')
    return redirect (url_for('my_view.login'))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base.css') }}">
    <title>Document</title>
</head>
<body>
    <div class="navigation">   
        <nav>
          <ul>
              <li><a href="{{ url_for('my_view.home') }}">Home</a></li>
              <li><a href="{{ url_for('my_view.registrationform')}}">Registar</a></li>
              <li><a href="{{ url_for('my_view.login') }}">Login</a></li>
              <li><a href="{{ url_for('my_view.logout')}}">Logout</a></li>
              <li><a href="#">Contact Us</a></li>
              <input type="text" class="searchbar" placeholder="Search..">
          </ul>
      </nav>
  </div> 
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
  {% block content %}
  {% endblock %}

</body>
</html>

project/templates/email_verification.html
{% extends 'base.html' %}
{% block content%}
<h1>ENTER YOUR OTP</h1>
<form method="post" action="">
    {{ form.csrf_token }}
    {{ form.otp_field.label }}
    {{ form.otp_field}}
    {{ form.submit }}
    <ul class = "error">
        {% for error in form.otp_field.errors %}
        <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
</form>
{% endblock %}

project/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>***WELCOME TO HOME PAGE***</h1>
<h3>YOU ARE SUCCESSFULLY REGISTER AND NOW LOGED IN </h3>
<br>
<br>
<h3>-----------DEMO PROJECT COMPLETED-----------</h3>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block content%}

<h1>LOGIN SYSTEM</h1>
<h3>This is a demo project using Flask <br></h3>
<p>write project description here....</p>
{% endblock %}

project/templates/login.html
{% extends 'base.html' %}
{% block content%}
<h3 class="heading">LOGIN SYSTEM DEMO PROJECT <br><br>LOGIN</h3>
<form class="login" method="POST" action="" novalidate>
    {{ form.csrf_token }}
    {{ form.username.label }}
    {{ form.username }}
    <ul class = "error">
        {% for error in form.username.errors %}
        <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.password.label }}
    {{ form.password }}
    <ul>
        {% for error in form.password.errors %}
        <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>   
    <label>
        <input type="checkbox", value="remember_me">
        Remember me
    </label> <br>
    <input type="submit" value="Submit">
    
</form>
{% endblock %}

project/templates/registration.html
{% extends 'base.html' %}
{% block content %}
<h3 class="heading_regi">REGISTRATION FORM</h3>
<form class="regi" method="POST" action="" novalidate>
    {{ form.csrf_token }}
    {{ form.name.label }}
    {{ form.name }}
    <ul>
        {% for error in form.name.errors %}
            <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.phone.label }}
    {{ form.phone }}
    <ul>
        {% for error in form.phone.errors %}
                <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.email.label}}
    {{ form.email}}
    <ul>
        {% for error in form.email.errors %}
            <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.password.label}}
    {{ form.password}}
    <ul>
        {% for error in form.password.errors %}
            <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.password_confirm.label }}
    {{ form.password_confirm}}
    <ul>
        {% for error in form.password_confirm.errors %}
            <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>

    <input type="submit" value="Submit">
</form>
{%endblock%}

project/templates/reset.html
{% extends 'base.html' %}
{% block content%}
<h1>Reset password</h1>
<form id="reset" method="POST" action="" novalidate>
    {{ form.csrf_token }}
    {{ form.new_password.label }}
    {{ form.new_password }}
    <ul>
        {% for error in form.new_password.errors %}
        <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {{ form.new_password_confirm.label }}
    {{ form.new_password_confirm}}
    <ul>
        {% for error in form.new_password_confirm.errors %}
            <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
   
    <input type="submit" value="Submit">
    
</form>
{% endblock %}